#Lab 4: Fundamentals of Tensor

---

##Basic operations

In [7]:
# Construct a one-dimensional tensor
import torch 
a = torch.ones(3) # Create a one-dimensional tensor of size 3 filled with 1s
a

tensor([1., 1., 1.])

In [ ]:
# Access an individual element in the tensor
a[1]

tensor(1.)

In [ ]:
# Assign a value to the thrid element of tensor
a[2] = 2.0
a

tensor([1., 1., 2.])

In [ ]:
# Create a tensor and assign values to the tensor
points = torch.zeros(6)
points[0] = 4.0
points[1] = 1.0
points[2] = 5.0
points[3] = 3.0
points[4] = 2.0
points[5] = 1.0
points

tensor([4., 1., 5., 3., 2., 1.])

In [ ]:
# Pass a Python list to the constructor
points = torch.tensor([4.0, 1.0, 5.0, 3.0, 2.0, 1.0])
points

tensor([4., 1., 5., 3., 2., 1.])

In [ ]:
# Create a 2D tensor
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [ ]:
# Examine the shape
points.shape

torch.Size([3, 2])

In [ ]:
# Use zeros or ones to initialize the tensor
points = torch.zeros(3, 2)
points

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [ ]:
# Pass a list of lists to the constructor
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [ ]:
# Access an individual element in the tensor using two indices
points[0, 1] # The output is another tensor

tensor(1.)

In [ ]:
# Access the first rwo of data
points[0] # The output is another tensor: the new tensor is a 1D tensor of size 2, referencing the values of the first row in the points tensor

tensor([4., 1.])

In [ ]:
# The subtensor (points[1]) is indexing the same storage as the original tensor
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point = points[1]
second_point[0] = 10.0
points

tensor([[ 4.,  1.],
        [10.,  3.],
        [ 2.,  1.]])

In [ ]:
# Clone the subtensor into a new tensor
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point = points[1].clone()
second_point[0] = 10.0
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

##Managing a tensor’s dtype attribute<br>

In [10]:
# Create two tensors with dtype=torch.double and torch.short
double_points = torch.ones(10, 2, dtype=torch.double)
short_points = torch.tensor([[1, 2], [3, 4]], dtype=torch.short)

In [11]:
# Examine a tensor's data type
short_points.dtype

torch.int16

In [15]:
# Convert data type using "to" method
double_points = torch.zeros(10, 2).to(torch.double)
short_points = torch.ones(10, 2).to(dtype=torch.short)

In [14]:
double_points.long()

tensor([[0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0]])

In [16]:
double_points.double()

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]], dtype=torch.float64)

##Transposing a tensor

In [17]:
# Create a 2D tensor
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [19]:
points.dtype

torch.float32

In [ ]:
# Transpose the tensor
points_t = points.t()
points_t

tensor([[10.,  5.,  2.],
        [ 1.,  3.,  1.]])

In [ ]:
# The transposed tensor shares the same storage
points_t[0,0] = 10.0
points

tensor([[10.,  1.],
        [ 5.,  3.],
        [ 2.,  1.]])

In [ ]:
# Transpose in higher dimensions
some_t = torch.ones(3, 4, 5)
transpose_t = some_t.transpose(0, 2)
transpose_t.shape

torch.Size([5, 4, 3])

In [ ]:
# The transposed tensor shares the same storage
transpose_t[0,0,0] = 0.0
some_t

tensor([[[0., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]])

## Enabling and testing the GPU

First, you'll need to enable GPUs for the notebook:

- Navigate to Edit→Notebook Settings
- select GPU from the Hardware Accelerator drop-down

In [ ]:
# Create a tensor on the GPU
import torch
points_gpu = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]], device='cuda')

In [ ]:
# Copy a tensor created on the CPU onto the GPU using the "to" method
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points
points_gpu = points.to(device='cuda')

In [ ]:
# At this point, any operation performed on the tensor, such as multiplying all elements by a constant, is carried out on the GPU
points_gpu = 2 * points.to(device='cuda')  #multiplication performed on the GPU
points_gpu = points_gpu + 4

In [ ]:
# move the tensor back to the CPU
points_cpu = points_gpu.to(device='cpu')

In [ ]:
# Use the shorthand methods cpu and cuda instead of the to method
points_gpu = points.cuda()
points_cpu = points_gpu.cpu()

##Save and load tensors

In [ ]:
#save the tensor
torch.save(points, '/content/drive/MyDrive/DL_data/ourpoints.t')

In [ ]:
#load the tensor
points = torch.load('/content/drive/MyDrive/DL_data/ourpoints.t')

## Representing tabular data<br>

In [1]:
# Mounting Google Drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
# Read data
import pandas as pd
carAuction = pd.read_csv("/content/drive/MyDrive/DL_data/carAuction.csv")
carAuction

,Auction,Color,IsBadBuy,MMRCurrentAuctionAveragePrice,Size,TopThreeAmericanName,VehBCost,VehicleAge,VehOdo,WarrantyCost,WheelType
0,ADESA,WHITE,No,2871,LARGE TRUCK,FORD,5300,8,75419,869,Alloy
1,ADESA,GOLD,Yes,1840,VAN,FORD,3600,8,82944,2322,Alloy
2,ADESA,RED,No,8931,SMALL SUV,CHRYSLER,7500,4,57338,588,Alloy
3,ADESA,GOLD,No,8320,CROSSOVER,FORD,8500,5,55909,1169,Alloy
4,ADESA,GREY,No,11520,LARGE TRUCK,FORD,10100,5,86702,853,Alloy
...,...,...,...,...,...,...,...,...,...,...,...
9995,ADESA,RED,No,7536,SMALL SUV,CHRYSLER,6600,4,85377,983,Alloy
9996,ADESA,BLACK,No,4921,LARGE TRUCK,GM,7000,7,89665,1543,Alloy
9997,ADESA,BLACK,No,9263,MEDIUM SUV,CHRYSLER,9000,4,59383,1417,Alloy
9998,ADESA,BLUE,No,3240,MEDIUM,OTHER,5500,4,48642,482,Covers
9999,ADESA,SILVER,No,6148,MEDIUM SUV,FORD,7000,5,82563,1243,Alloy

In [3]:
# Create dummy variables
carAuction = pd.get_dummies(carAuction, columns=['IsBadBuy','Auction','Color','Size','TopThreeAmericanName','WheelType'],drop_first=True)
carAuction

,MMRCurrentAuctionAveragePrice,VehBCost,VehicleAge,VehOdo,WarrantyCost,IsBadBuy_Yes,Auction_MANHEIM,Auction_OTHER,Color_BLACK,Color_BLUE,...,Size_SMALL TRUCK,Size_SPECIALTY,Size_SPORTS,Size_VAN,TopThreeAmericanName_FORD,TopThreeAmericanName_GM,TopThreeAmericanName_OTHER,WheelType_Covers,WheelType_Special,WheelType_unkwnWheel
0,2871,5300,8,75419,869,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
1,1840,3600,8,82944,2322,1,0,0,0,0,...,0,0,0,1,1,0,0,0,0,0
2,8931,7500,4,57338,588,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,8320,8500,5,55909,1169,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
4,11520,10100,5,86702,853,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,7536,6600,4,85377,983,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9996,4921,7000,7,89665,1543,0,0,0,1,0,...,0,0,0,0,0,1,0,0,0,0
9997,9263,9000,4,59383,1417,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
9998,3240,5500,4,48642,482,0,0,0,0,1,...,0,0,0,0,0,0,1,1,0,0
9999,6148,7000,5,82563,1243,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0

In [5]:
# Apply standardization
from sklearn.preprocessing import StandardScaler
numeric_variables = carAuction[['MMRCurrentAuctionAveragePrice', 'VehBCost', 'VehicleAge', 'VehOdo', 'WarrantyCost']]
scaler_s = StandardScaler().fit(numeric_variables)
standard_variables = scaler_s.transform(numeric_variables)
print(standard_variables)
carAuction[['MMRCurrentAuctionAveragePrice', 'VehBCost', 'VehicleAge', 'VehOdo', 'WarrantyCost']] = standard_variables

[[-1.33756114 -0.80983074  2.22646285  0.26402682 -0.67480576]
 [-1.7625022  -1.77920496  2.22646285  0.77636434  1.71108844]
 [ 1.16015257  0.44465355 -0.1066831  -0.96701301 -1.13622094]
 ...
 [ 1.29699102  1.29998375 -0.1066831  -0.82777976  0.22503596]
 [-1.18547263 -0.69578671 -0.1066831  -1.55907774 -1.31027792]
 [ 0.01310022  0.15954349  0.47660339  0.75042406 -0.0606802 ]]

In [8]:
# Create tensors from pandas dataframe
carAuction_tensor = torch.tensor(carAuction.values)
carAuction_tensor

tensor([[-1.3376, -0.8098,  2.2265,  ...,  0.0000,  0.0000,  0.0000],
        [-1.7625, -1.7792,  2.2265,  ...,  0.0000,  0.0000,  0.0000],
        [ 1.1602,  0.4447, -0.1067,  ...,  0.0000,  0.0000,  0.0000],
        ...,
        [ 1.2970,  1.3000, -0.1067,  ...,  0.0000,  0.0000,  0.0000],
        [-1.1855, -0.6958, -0.1067,  ...,  1.0000,  0.0000,  0.0000],
        [ 0.0131,  0.1595,  0.4766,  ...,  0.0000,  0.0000,  0.0000]],
       dtype=torch.float64)

In [9]:
# From tensor to pandas dataframe
carAuction_df = pd.DataFrame(carAuction_tensor.tolist())
carAuction_df

,0,1,2,3,4,5,6,7,8,9,...,30,31,32,33,34,35,36,37,38,39
0,-1.337561,-0.809831,2.226463,0.264027,-0.674806,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
1,-1.762502,-1.779205,2.226463,0.776364,1.711088,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0
2,1.160153,0.444654,-0.106683,-0.967013,-1.136221,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.908320,1.014874,0.476603,-1.064306,-0.182192,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
4,2.227245,1.927226,0.476603,1.032227,-0.701079,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,0.585184,-0.068545,-0.106683,0.942014,-0.487612,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9996,-0.492625,0.159543,1.643176,1.233962,0.431934,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
9997,1.296991,1.299984,-0.106683,-0.827780,0.225036,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9998,-1.185473,-0.695787,-0.106683,-1.559078,-1.310278,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0
9999,0.013100,0.159543,0.476603,0.750424,-0.060680,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
!jupyter nbconvert --to html "/content/drive/MyDrive/DL_lab/Lab 4: Fundamentals of Tensor Solution.ipynb"